In [1]:
import numpy as np

In [4]:
np?

Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

In [6]:
L = list(range(1,10))

In [7]:
L

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [11]:
[type(item) for item in L]

[int, int, int, int, int, int, int, int, int]

In [15]:
#we can create hetrogenous list as well but that is not memory efficent and slow

L1= [True,2,3.4,"2"]

In [13]:
L1

[True, 2, 3.4, '2']

In [14]:
[type(item) for item in L1]

[bool, int, float, str]

In [17]:
L2=np.array(L1)

In [18]:
L2

array(['True', '2', '3.4', '2'], dtype='<U32')

In [19]:
[type(item) for item in L2]

[numpy.str_, numpy.str_, numpy.str_, numpy.str_]

In [233]:
#Array converts all inputs into same type to make it more memory efficient

In [22]:
#e.g 
np.array([3.14, 4, 2, 3])  # convert all in floats

array([3.14, 4.  , 2.  , 3.  ])

In [23]:
#If we want to explicitly set the data type of the resulting array, we can use the dtype
#keyword:

np.array([1,2,3,4],dtype='float')

array([1., 2., 3., 4.])

In [24]:
#Creating Arrays from Scratch


np.zeros(10,dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [25]:
np.ones(10,dtype=float)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [27]:
## Create a 3x5 int array filled with 1s

np.ones((3,5),dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [31]:
# Create a 3x5 floating-point array filled with 2

np.full((3,5),2)

array([[2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2]])

In [37]:
np.arange(0,20,2) # it is similar to 'range' function

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [41]:
# Create an array of five values evenly spaced between 0 and 1

np.linspace(0,1,5)  # from 0 to 5 with 5 equal spaces

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [50]:
# Create a 3x3 array of uniformly distributed
# random values between 0 and 1

np.random.random((3,3))

#random_sample(size=None) >Return random floats in the half-open interval [0.0, 1.0).


array([[0.38460407, 0.46371968, 0.67004825],
       [0.4868439 , 0.39917263, 0.07281453],
       [0.26800982, 0.85676521, 0.28917252]])

In [52]:
# Create a 3x3 array of normally distributed random values
# with mean 0 and standard deviation 1

np.random.normal?

# Parameters
# ----------
# loc : float or array_like of floats
#     Mean ("centre") of the distribution.
# scale : float or array_like of floats
#     Standard deviation (spread or "width") of the distribution.
# size : int or tuple of ints, optional
#     Output shape.  If the given shape is, e.g., ``(m, n, k)``, then
#     ``m * n * k`` samples are drawn.  If size is ``None`` (default),
#     a single value is returned if ``loc`` and ``scale`` are both scalars.
#     Otherwise, ``np.broadcast(loc, scale).size`` samples are drawn.

In [53]:
np.random.normal(0,1,(3,3))

array([[-0.03297636, -0.03244807, -0.27253689],
       [ 1.76648532,  0.45881968,  0.65269664],
       [ 0.44806458,  0.36574905,  0.52478597]])

In [57]:
# Create a 3x3 array of random integers in the interval [0, 10)

np.random.randint?



In [61]:
np.random.randint(0,10,(3,3),dtype='int32')

array([[0, 0, 3],
       [4, 9, 3],
       [1, 2, 4]])

# The Basics of NumPy Arrays:

1)Attributes of arrays >  Determining the size, shape, memory consumption, and data types of arrays

2)Indexing of arrays >  Getting and setting the value of individual array elements

3)Slicing of arrays >  Getting and setting smaller subarrays within a larger array

4)Reshaping of arrays >  Changing the shape of a given array

5)Joining and splitting of arrays >  Combining multiple arrays into one, and splitting one array into many

In [65]:
x1 = np.random.randint(10,size =6) #One dimensional array

x1

array([4, 8, 8, 3, 6, 2])

In [67]:
x2 = np.random.randint(10,size=(2,3)) #two demensional array

x2

array([[1, 1, 2],
       [0, 7, 1]])

In [69]:
x3 = np.random.randint(10, size=(3, 4, 5)) # Three-dimensional array , size(no. of array,no. of rows for each, column)

x3

array([[[6, 1, 5, 8, 0],
        [0, 3, 5, 6, 2],
        [3, 7, 4, 5, 2],
        [0, 7, 4, 9, 3]],

       [[1, 5, 9, 7, 3],
        [8, 0, 2, 3, 2],
        [0, 8, 6, 2, 2],
        [1, 9, 8, 4, 6]],

       [[9, 5, 5, 5, 5],
        [9, 1, 4, 7, 4],
        [3, 2, 0, 6, 7],
        [1, 9, 4, 9, 6]]])

In [71]:
x3.min()

0

In [73]:
x3.ndim  #give dimention of array

3

In [74]:
x3.shape

(3, 4, 5)

In [75]:
x3.size  # total samples in array

60

In [76]:
x1[2]  # array indexing

8

In [83]:
x2[1][1]   # two dimensional indexing

7

In [87]:
x3[0,0]

array([6, 1, 5, 8, 0])

In [89]:
x3[1,2,3]  # 2nd array , 2nd row and  third element

2

In [90]:
# Array slicing :   x[start:stop:step]

x1[2:]

array([8, 3, 6, 2])

In [91]:
x1[::-1]  # reversing 

array([2, 6, 3, 8, 8, 4])

In [101]:
#multidimensional array slicing


x2[:1,:3] # one row and tow column

array([[1, 1, 2]])

In [105]:
x2[::-1,:]  # rows reversed

array([[0, 7, 1],
       [1, 1, 2]])

In [107]:
x2[:,::-1]  # columns value reversed

array([[2, 1, 1],
       [1, 7, 0]])

In [108]:
#Why we need numpy. lets see one example

x = [1,2,3]
y= [4,5,6]

x+y # adding will it give right ans?

[1, 2, 3, 4, 5, 6]

In [109]:
# no here comes the use of numpy

x_arr = np.array(x)

y_arr= np.array(y)

x_arr+y_arr

array([5, 7, 9])

In [110]:
#Now its giving correct ans

# Array Concatenation and Splitting:

In [111]:
 x = np.array([1,2,3])
y= np.array([4,5,6])

In [113]:
x+y # it will give sum of two 

array([5, 7, 9])

In [115]:
np.concatenate([x,y])

array([1, 2, 3, 4, 5, 6])

In [117]:
z= np.array([7,8,9])

In [118]:
print(np.concatenate([x,y,z]))

[1 2 3 4 5 6 7 8 9]


In [129]:
x= np.array([1,2,3])
y= np.arange(9).reshape((3,3))

In [131]:
np.vstack([x,y])

array([[1, 2, 3],
       [0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [133]:
x.ndim

1

In [134]:
y.ndim

2

In [135]:
y

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [150]:
# dimension of x and y should be same for hstack

x = np.array([[1],[4],[7]])

In [151]:
x

array([[1],
       [4],
       [7]])

In [152]:
x.ndim

2

In [153]:
np.hstack([x,y])

array([[1, 0, 1, 2],
       [4, 3, 4, 5],
       [7, 6, 7, 8]])

In [154]:
x = [1, 2, 3, 99, 99, 3, 2, 1]
x1, x2, x3 = np.split(x, [3, 5])  # split at 3rd to 4th position
print(x1, x2, x3)

[1 2 3] [99 99] [3 2 1]


In [155]:
x = [1, 2, 3, 99, 99, 3, 2, 1]
x1, x2, x3 = np.split(x, [3, 6])
print(x1, x2, x3)

[1 2 3] [99 99  3] [2 1]


In [159]:
X = np.random.random((10, 3))

In [160]:
X

array([[0.35465532, 0.32621083, 0.75410795],
       [0.00532932, 0.26591084, 0.87037221],
       [0.98538053, 0.49879071, 0.40480937],
       [0.19449636, 0.78683233, 0.80933447],
       [0.32463296, 0.30349202, 0.07761932],
       [0.32240292, 0.32574472, 0.83743413],
       [0.22719505, 0.295416  , 0.41272575],
       [0.38350931, 0.59748692, 0.95663754],
       [0.98355327, 0.99277827, 0.48225052],
       [0.76141031, 0.15302016, 0.07906879]])

# Access  specific element , row , column

In [161]:
#Lets create two dimensional array

a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])

In [162]:
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [163]:
a.ndim

2

In [164]:
a.shape

(2, 7)

In [165]:
#acessing in format row, column

a[0,] #first row

array([1, 2, 3, 4, 5, 6, 7])

In [167]:
a[1,]  #second row

array([ 8,  9, 10, 11, 12, 13, 14])

In [168]:
a[0,5] # fith element of first row

6

In [170]:
a[0,:]  # same for first row in fancy way

array([1, 2, 3, 4, 5, 6, 7])

In [171]:
a[:, 2] # all row specific column

array([ 3, 10])

In [172]:
#specific range of column , [start:end:stepsize]

a[0,2:6]

array([3, 4, 5, 6])

In [174]:
a[0,1:6:2]

array([2, 4, 6])

In [175]:
#Note we can use negative indexing as well same as list

In [176]:
#Changing any specific element in array

a[0,5]=20    #first row 6th element

In [177]:
print(a)

[[ 1  2  3  4  5 20  7]
 [ 8  9 10 11 12 13 14]]


In [179]:
#Changing specific column

a[:,2] = [30,140]

In [181]:
print(a) # 3rd row changed with assigned values

[[  1   2  30   4   5  20   7]
 [  8   9 140  11  12  13  14]]


In [182]:
#3-d example

b = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

In [183]:
b

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [185]:
# to access the 3-d array work outside in method

b[0,1,2]  # first box of array, 2nd row , 3rd column element

6

In [187]:
b[:,1,:] # all box , 2nd row of each, all columns

array([[ 4,  5,  6],
       [10, 11, 12]])

In [189]:
b[:,1,::-1]  # we should get reversed number now

array([[ 6,  5,  4],
       [12, 11, 10]])

# Intializing different types of array

In [191]:
#all 0's matrix

print(np.zeros((2,3),dtype='int8'))

[[0 0 0]
 [0 0 0]]


In [192]:
#all 1's matrix

print(np.ones((2,3),dtype='int16'))

[[1 1 1]
 [1 1 1]]


In [203]:
#any number

print(np.full((2,3),16))

[[16 16 16]
 [16 16 16]]


# Be carefull when copying array!

In [211]:
a = np.array([1,2,3,4])

b= a

print(b)

[1 2 3 4]


In [206]:
#lets change value in b not a

b[1]= 100

print(b)

[  1 100   3   4]


In [207]:
#now lets check a also

print(a)

[  1 100   3   4]


In [212]:
#here a changed too it means array won't copy actually b is just view of a only
#So to prevent this

b=a.copy()

In [213]:
b

array([1, 2, 3, 4])

In [214]:
b[2]= 100

In [215]:
print(b)

[  1   2 100   4]


In [216]:
print(a)

[1 2 3 4]


In [217]:
#Now you can see that a presist its own value not changed

# Mathematics with array

In [218]:
c = np.array([1,2,3,4])

In [219]:
print(c+5)

[6 7 8 9]


In [220]:
c/5

array([0.2, 0.4, 0.6, 0.8])

In [221]:
c*5

array([ 5, 10, 15, 20])

In [222]:
c**2

array([ 1,  4,  9, 16], dtype=int32)

In [223]:
c//5 


array([0, 0, 0, 0], dtype=int32)

# Linear Algebra


In [226]:
a= np.ones([2,3])
a

b= np.full([3,2],4)
b

array([[4, 4],
       [4, 4],
       [4, 4]])

In [232]:
np.matmul(a,b)   # it matrix multipication not direct multiplication otherwise it will give error because both array
#is of different size so for liner multiplication matrix should be in (n,k) and (k,m) >(n,m)output format

array([[12., 12.],
       [12., 12.]])

# Stat with Array

In [234]:
a = np.array([[1,2,3],[4,5,6]])

In [235]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [236]:
a.max() # max value in a


6

In [237]:
a.min() # min value in a

1

In [238]:
a.sum() # some of values

21

In [239]:
a.mean()

3.5

In [241]:
print(a.cumsum()) # will give cummulative sum

[ 1  3  6 10 15 21]


# Resizing of array

In [243]:
a.shape

(2, 3)

In [246]:
a.reshape(3,2)  # will create the same array of 3 x 2 matrix

array([[1, 2],
       [3, 4],
       [5, 6]])

In [248]:
a.reshape(6,1)  #6 x1 dimensional

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

# Boolean masking

In [249]:
a= np.array([[1,2,3],[4,5,6]])

In [250]:
a >3

array([[False, False, False],
       [ True,  True,  True]])

In [255]:
np.sum(a>3)  # it will give count of values greater than 3 , as here sum , suming up the true bool values only

3

In [257]:
np.any(a>3)  # is any value greater than 3 in a

True

In [262]:
np.full((2,3),a>3)

array([[False, False, False],
       [ True,  True,  True]])

In [263]:
((a>2)& (a<5))

array([[False, False,  True],
       [ True, False, False]])

In [266]:
np.sum((a>2)& (a<5))  # two value greater than 2 and less than 5

2

# Operator: 

1) "&" > np.bitwise_and
2) "|" > np.bitwise_or
3) "^" > np.bitwise_xor
4) "~" > np.bitwise_not

# Some additional cool stuff:

Numpy YT video ://www.youtube.com/watch?v=QUT1VHiLmmI

🔗 Array Creation Routines: https://docs.scipy.org/doc/numpy/reference/routines.array-creation.html
🔗 Math Routines Docs: https://docs.scipy.org/doc/numpy/reference/routines.math.html
🔗 Linear Algebra Docs: https://docs.scipy.org/doc/numpy/reference/routines.linalg.html

In [268]:
#Sorting of array

a= np.array([2,5,6,1,3,0,4])
print(a)

[2 5 6 1 3 0 4]


In [269]:
print(np.sort(a))

[0 1 2 3 4 5 6]


In [273]:
#Sorting by row or column

b= np.random.randint(1,10,(6,7))

In [274]:
b

array([[3, 6, 2, 4, 6, 1, 9],
       [1, 4, 1, 1, 5, 7, 9],
       [4, 6, 1, 4, 5, 8, 2],
       [5, 1, 3, 1, 4, 4, 5],
       [7, 4, 8, 6, 1, 1, 7],
       [5, 2, 5, 9, 9, 9, 5]])

In [275]:
#sorting along all columns:

np.sort(b,axis= 0)

array([[1, 1, 1, 1, 1, 1, 2],
       [3, 2, 1, 1, 4, 1, 5],
       [4, 4, 2, 4, 5, 4, 5],
       [5, 4, 3, 4, 5, 7, 7],
       [5, 6, 5, 6, 6, 8, 9],
       [7, 6, 8, 9, 9, 9, 9]])

In [276]:
# sorting along all rows

np.sort(b,axis=1)

array([[1, 2, 3, 4, 6, 6, 9],
       [1, 1, 1, 4, 5, 7, 9],
       [1, 2, 4, 4, 5, 6, 8],
       [1, 1, 3, 4, 4, 5, 5],
       [1, 1, 4, 6, 7, 7, 8],
       [2, 5, 5, 5, 9, 9, 9]])

# Partial Sorts: Partitioning

Sometimes we’re not interested in sorting the entire array, but simply want to find the
K smallest values in the array. NumPy provides this in the np.partition function.
np.partition takes an array and a number K; the result is a new array with the smallest
K values to the left of the partition, and the remaining values to the right, in arbitrary
order:

In [277]:
x= np.array([4,1,2,3,7,6,4,8])

In [279]:
x

array([4, 1, 2, 3, 7, 6, 4, 8])

In [284]:
np.partition(x,3)  # it sort the less than 3 on left side in random manner ,rest on right

array([2, 1, 3, 4, 4, 6, 7, 8])

In [286]:
np.sort(np.partition(x,3)) # if we want to sort further arount specific K then , we can use like this

array([1, 2, 3, 4, 4, 6, 7, 8])

# Creating structured Array

In [319]:
name = ['Alice', 'Bob', 'Cathy', 'Doug']
age = [25, 45, 37, 19]
weight = [55.0, 85.5, 68.0, 61.5]

data =np.zeros(4,dtype={'names':('name','age','weight'),'formats':((np.str,10),int,float)})

In [320]:
data['name']= name
data['age']= age
data['weight']= weight

In [321]:
print(data)

[('Alice', 25, 55. ) ('Bob', 45, 85.5) ('Cathy', 37, 68. )
 ('Doug', 19, 61.5)]
