In [145]:
import numpy as np 

from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"     # to print all values not only last

# Basic

In [3]:
a= np.array([1,2,3])
print(a)

[1 2 3]


In [4]:
b= np.array([1,2.3,1.0 , 4,5]) #numpy upcast the datatype
print(b)

[1.  2.3 1.  4.  5. ]


In [6]:
c = np.array([[1,2,3,4],[5,6,7,8]]) #2D array
print(c)

[[1 2 3 4]
 [5 6 7 8]]


In [8]:
#to check dimension of array

b.ndim

1

In [9]:
c.ndim

2

In [10]:
#Shape of array
b.shape

(5,)

In [11]:
c.shape

(2, 4)

In [12]:
b.size

5

In [13]:
c.size

8

In [15]:
#Get type
b.dtype

dtype('float64')

In [16]:
#if we want to change type of array
b = np.array([1,2.3,1.0 , 4,5],dtype='float32')
b

array([1. , 2.3, 1. , 4. , 5. ], dtype=float32)

In [17]:
b.dtype

dtype('float32')

In [18]:
b = np.array([1,2.3,1.0 , 4,5],dtype='int32')

In [19]:
b

array([1, 2, 1, 4, 5])

In [20]:
b.dtype

dtype('int32')

In [21]:
b.itemsize

4

In [24]:
# itemsize size gives us how many byte item occupying in array

In [26]:
# To get total byte of array
b.itemsize*b.size   #in bytes

20

In [27]:
#Another way to get Total size of array

b.nbytes

20

# Accessing/changing specific element, column, row etc

In [42]:
d = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
d

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [32]:
# Get specific element array[row,column]
# Lets get 11 from d

d[1,3]    #Note:index start from 0(zero)

11

In [33]:
#get specific row
d[0,]

array([1, 2, 3, 4, 5, 6, 7])

In [34]:
d[1,]

array([ 8,  9, 10, 11, 12, 13, 14])

In [36]:
#Get specific column  , Lets get 4th column

d[:,3]

array([ 4, 11])

In [37]:
#To get range of values, here concept is same like list(slicing/indexing)

d[0,2:6:3]

array([3, 6])

In [43]:
#Changing spefic element
#lets change 12 with 24

d[1,4]=24

In [44]:
d

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 24, 13, 14]])

In [45]:
#Changing complete column

d[:,2] = [100,200]
d

array([[  1,   2, 100,   4,   5,   6,   7],
       [  8,   9, 200,  11,  24,  13,  14]])

In [46]:
#Array is very flexible to change any element/row/column

# 3 D Array

In [47]:
e = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
e

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [50]:
e.ndim

3

In [51]:
e.size

9

In [52]:
e.nbytes

36

In [55]:
#Accessing spcefic element,6
e[0,1,2]      #(sheet/dimensional axis,row,column)

6

In [56]:
#Another 3 Exmaple

f = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
f

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [57]:
f[1,1,1]   # to get 11

11

In [59]:
#Above in f we are first accessing second sheet table which has index 1 as its starting 
#from 0, then we are accessing row which is 2nd row with index 1, third we are acessing 
#2nd column which is also with index 1 as strating from 0(index)

In [61]:
f.sum(axis=0) # it sums up all first row with frist row , 2nd with second .....

array([[ 8, 10, 12],
       [14, 16, 18]])

In [67]:
f.sum(0) # we can sum up elements by axis , we can omit axis keyword

array([[ 8, 10, 12],
       [14, 16, 18]])

In [69]:
f.sum(1)  # first row is sum of first sheet rows, so on

array([[ 5,  7,  9],
       [17, 19, 21]])

In [71]:
f.sum(2) # sum of rows, in rows with respect to sheet

array([[ 6, 15],
       [24, 33]])

In [73]:
#we can crete array of all the summation axis also

f.sum(0),f.sum(1),f.sum(2)

(array([[ 8, 10, 12],
        [14, 16, 18]]), array([[ 5,  7,  9],
        [17, 19, 21]]), array([[ 6, 15],
        [24, 33]]))

In [74]:
#Accessing
f[:,1,:] # all sheet,2nd row of each sheet, all columns

array([[ 4,  5,  6],
       [10, 11, 12]])

In [75]:
f[:,:,0] #all sheet,all rows,1st column

array([[ 1,  4],
       [ 7, 10]])

In [76]:
#Replacing any element in 3d array

f[1,1,2] = 100
f

array([[[  1,   2,   3],
        [  4,   5,   6]],

       [[  7,   8,   9],
        [ 10,  11, 100]]])

In [77]:
#Successfully changed 

# Initializing different types of arrays

In [78]:
#Zero matrix
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [80]:
np.zeros((3,3)) # 2d 0's array

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [81]:
#ones matrix
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [83]:
np.ones((2,3),dtype='int16')

array([[1, 1, 1],
       [1, 1, 1]], dtype=int16)

In [85]:
#Specific number matrix

np.full((3,3),99)

array([[99, 99, 99],
       [99, 99, 99],
       [99, 99, 99]])

In [87]:
np.full_like(f,10)  # it means fill same array a 'f' with value 10

array([[[10, 10, 10],
        [10, 10, 10]],

       [[10, 10, 10],
        [10, 10, 10]]])

In [90]:
#with random values

np.random.randint(10,size=6)

array([0, 6, 6, 1, 5, 6])

In [91]:
np.random.randint(10,size=(2,3))

array([[9, 2, 2],
       [8, 4, 2]])

In [92]:
np.random.randint(10,size=(3,3,3))

array([[[9, 0, 5],
        [1, 6, 1],
        [5, 8, 0]],

       [[0, 1, 7],
        [2, 2, 1],
        [5, 9, 4]],

       [[9, 0, 0],
        [0, 9, 6],
        [9, 8, 3]]])

In [95]:
np.random.rand(3,3) #filled the array with uniform distribution(0 to 1)

array([[0.60007321, 0.40236405, 0.30371585],
       [0.68596652, 0.26478986, 0.45084733],
       [0.77022932, 0.7498803 , 0.17268411]])

In [96]:
np.random.rand(3)

array([0.6059677 , 0.06681694, 0.73071832])

In [101]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [103]:
#Now lets built one matrix using above concepts

#matrix :
 
# 1 1 1 1 1
# 1 0 0 0 1
# 1 0 9 0 1
# 1 0 0 0 1
# 1 1 1 1 1

In [107]:
#Above one seems 5 by 5 matrix

g = np.ones((5,5),dtype='int32')
g

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [108]:
g[1:4,1:4] = np.zeros((3,3))
g

array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]])

In [109]:
g[2,2]=9
g

array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 9, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]])

In [110]:
#Successfully done.. Hurry !

# Careful while copying array to other 

In [111]:
#e.g

h = np.array([1,2,3])
h

array([1, 2, 3])

In [112]:
i=h
i[2]=100
i

array([  1,   2, 100])

In [113]:
#now lets check the h also but remeber we didn't change anything in h
h

array([  1,   2, 100])

In [114]:
#Strange isn't it? Actually we assign direct identity of h to i thats why both changed so
#always copy like below

i=h.copy()
i[2] = 200

In [115]:
i

array([  1,   2, 200])

In [117]:
#now 'h' should be same as before with 100

h

array([  1,   2, 100])

# Mathematics with Array

In [118]:
j = np.array([1,2,3,4,5])
j

array([1, 2, 3, 4, 5])

In [121]:
j+2

array([3, 4, 5, 6, 7])

In [122]:
j-2

array([-1,  0,  1,  2,  3])

In [123]:
j*2

array([ 2,  4,  6,  8, 10])

In [124]:
j/2

array([0.5, 1. , 1.5, 2. , 2.5])

In [125]:
#we can do math with another array also

j + np.array([10,11,12,13,14])

array([11, 13, 15, 17, 19])

In [132]:
j*np.array([5])

array([ 5, 10, 15, 20, 25])

In [133]:
j**2

array([ 1,  4,  9, 16, 25], dtype=int32)

In [146]:
#Lets learn how do liner algebra with matrix

k = np.ones((2,3),dtype='int32')
k

l = np.full((3,2),3)
l

array([[1, 1, 1],
       [1, 1, 1]])

array([[3, 3],
       [3, 3],
       [3, 3]])

In [142]:
#if we do

k*l  # it will give error, as you remeber in matrix multiplication happen in some differnt
    # way like Row of first matrix multiple to column of next matrix
    
#so we have special fun for that


ValueError: operands could not be broadcast together with shapes (2,3) (3,2) 

In [144]:
np.matmul(k,l) #Matrix product of two arrays.

array([[9, 9],
       [9, 9]])

In [154]:
np.identity(5,dtype= 'int32')

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [159]:
np.linalg.det(np.identity(5,dtype= 'int32'))  #determinant

1.0

In [163]:
#Tranpose of matrix

M = np.array([[1,2,3],[4,5,6]])
M

array([[1, 2, 3],
       [4, 5, 6]])

In [165]:
M.transpose()

array([[1, 4],
       [2, 5],
       [3, 6]])

# Stat with Array

In [166]:
M.min()

1

In [170]:
M.min(axis=1) # action performs on row
M.min(axis = 0) # action performs on column

array([1, 4])

array([1, 2, 3])

In [171]:
M.max()

6

In [172]:
M.max(axis=0)
M.max(axis= 1)

array([4, 5, 6])

array([3, 6])

In [174]:
M.mean()

3.5

In [175]:
M.mean(axis=0) #action performs on columns(sum of one column/no. of element in one column)

array([2.5, 3.5, 4.5])

In [176]:
M.mean(axis= 1)

array([2., 5.])

# Rearranding Array

In [186]:
M.shape

(2, 3)

In [190]:
M
M.reshape((3,2))
M.reshape((6,1))

array([[1, 2, 3],
       [4, 5, 6]])

array([[1, 2],
       [3, 4],
       [5, 6]])

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [192]:
n = np.array([7,8,9])
n
M

array([7, 8, 9])

array([[1, 2, 3],
       [4, 5, 6]])

In [194]:
np.vstack([M,n]) 

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [200]:
M[M>4]

array([5, 6])

In [201]:
np.any(M>4)

True

In [202]:
np.all(M>4)

False